/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups.index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedGroupsNewRouteImport } from './routes/_authed/groups.new'
import { Route as AuthedGroupsGroupIdIndexRouteImport } from './routes/_authed/groups.$groupId.index'
import { Route as AuthedGroupsGroupIdMembersRouteImport } from './routes/_authed/groups.$groupId.members'
import { Route as AuthedGroupsGroupIdBalancesRouteImport } from './routes/_authed/groups.$groupId.balances'
import { Route as AuthedGroupsGroupIdExpensesNewRouteImport } from './routes/_authed/groups.$groupId.expenses.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedGroupsNewRoute = AuthedGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsGroupIdIndexRoute =
  AuthedGroupsGroupIdIndexRouteImport.update({
    id: '/groups/$groupId/',
    path: '/groups/$groupId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsGroupIdMembersRoute =
  AuthedGroupsGroupIdMembersRouteImport.update({
    id: '/groups/$groupId/members',
    path: '/groups/$groupId/members',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsGroupIdBalancesRoute =
  AuthedGroupsGroupIdBalancesRouteImport.update({
    id: '/groups/$groupId/balances',
    path: '/groups/$groupId/balances',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsGroupIdExpensesNewRoute =
  AuthedGroupsGroupIdExpensesNewRouteImport.update({
    id: '/groups/$groupId/expenses/new',
    path: '/groups/$groupId/expenses/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/groups/new': typeof AuthedGroupsNewRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/groups/$groupId/balances': typeof AuthedGroupsGroupIdBalancesRoute
  '/groups/$groupId/members': typeof AuthedGroupsGroupIdMembersRoute
  '/groups/$groupId/': typeof AuthedGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AuthedGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/groups/new': typeof AuthedGroupsNewRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/groups/$groupId/balances': typeof AuthedGroupsGroupIdBalancesRoute
  '/groups/$groupId/members': typeof AuthedGroupsGroupIdMembersRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AuthedGroupsGroupIdExpensesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/_authed/groups/new': typeof AuthedGroupsNewRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/groups/$groupId/balances': typeof AuthedGroupsGroupIdBalancesRoute
  '/_authed/groups/$groupId/members': typeof AuthedGroupsGroupIdMembersRoute
  '/_authed/groups/$groupId/': typeof AuthedGroupsGroupIdIndexRoute
  '/_authed/groups/$groupId/expenses/new': typeof AuthedGroupsGroupIdExpensesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/dashboard'
    | '/posts'
    | '/auth/confirm'
    | '/groups/new'
    | '/posts/$postId'
    | '/groups/'
    | '/posts/'
    | '/groups/$groupId/balances'
    | '/groups/$groupId/members'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/dashboard'
    | '/auth/confirm'
    | '/groups/new'
    | '/posts/$postId'
    | '/groups'
    | '/posts'
    | '/groups/$groupId/balances'
    | '/groups/$groupId/members'
    | '/groups/$groupId'
    | '/groups/$groupId/expenses/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/posts'
    | '/auth/confirm'
    | '/_authed/groups/new'
    | '/_authed/posts/$postId'
    | '/_authed/groups/'
    | '/_authed/posts/'
    | '/_authed/groups/$groupId/balances'
    | '/_authed/groups/$groupId/members'
    | '/_authed/groups/$groupId/'
    | '/_authed/groups/$groupId/expenses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/groups/new': {
      id: '/_authed/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthedGroupsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId/': {
      id: '/_authed/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AuthedGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId/members': {
      id: '/_authed/groups/$groupId/members'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof AuthedGroupsGroupIdMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId/balances': {
      id: '/_authed/groups/$groupId/balances'
      path: '/groups/$groupId/balances'
      fullPath: '/groups/$groupId/balances'
      preLoaderRoute: typeof AuthedGroupsGroupIdBalancesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId/expenses/new': {
      id: '/_authed/groups/$groupId/expenses/new'
      path: '/groups/$groupId/expenses/new'
      fullPath: '/groups/$groupId/expenses/new'
      preLoaderRoute: typeof AuthedGroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedGroupsNewRoute: typeof AuthedGroupsNewRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedGroupsGroupIdBalancesRoute: typeof AuthedGroupsGroupIdBalancesRoute
  AuthedGroupsGroupIdMembersRoute: typeof AuthedGroupsGroupIdMembersRoute
  AuthedGroupsGroupIdIndexRoute: typeof AuthedGroupsGroupIdIndexRoute
  AuthedGroupsGroupIdExpensesNewRoute: typeof AuthedGroupsGroupIdExpensesNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedGroupsNewRoute: AuthedGroupsNewRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedGroupsGroupIdBalancesRoute: AuthedGroupsGroupIdBalancesRoute,
  AuthedGroupsGroupIdMembersRoute: AuthedGroupsGroupIdMembersRoute,
  AuthedGroupsGroupIdIndexRoute: AuthedGroupsGroupIdIndexRoute,
  AuthedGroupsGroupIdExpensesNewRoute: AuthedGroupsGroupIdExpensesNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
